name: kinetic_log
description: "Tu fuerza, tus datos. Sin registros, sin rodeos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.2

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Ads
  google_mobile_ads: ^5.1.0

  # Export
  pdf: ^3.10.8
  printing: ^5.12.0
  excel: ^4.0.3

  # Sharing
  share_plus: ^9.0.0

  # File handling
  file_picker: ^8.0.3
  open_filex: ^4.5.0
  permission_handler: ^11.3.1

  # UI
  percent_indicator: ^4.2.3
  table_calendar: ^3.1.2
  fl_chart: ^0.67.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.0

  # Utils
  intl: ^0.19.0
  uuid: ^4.4.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

flutter_launcher_icons:
  android: "ic_launcher"
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#0F0F0F"
  adaptive_icon_foreground: "assets/images/icon.png"
  min_sdk_android: 24

flutter_native_splash:
  color: "#0F0F0F"
  image: assets/images/logo.png
  android_12:
    color: "#0F0F0F"
    image: assets/images/logo.png
